# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QtWidgetsApplication1Class(object):
    def setupUi(self, QtWidgetsApplication1Class):
        QtWidgetsApplication1Class.setObjectName("QtWidgetsApplication1Class")
        QtWidgetsApplication1Class.setEnabled(True)
        QtWidgetsApplication1Class.resize(1106, 884)
        self.centralWidget = QtWidgets.QWidget(QtWidgetsApplication1Class)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(self.centralWidget)
        self.widget_5.setMinimumSize(QtCore.QSize(200, 150))
        self.widget_5.setObjectName("widget_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_5.setGeometry(QtCore.QRect(9, 9, 251, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 100, 251, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 70, 251, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 40, 251, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.widget_5, 1, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralWidget)
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 40, 61, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(100, 40, 31, 21))
        self.label_12.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 31, 21))
        self.label_8.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(70, 40, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 31, 21))
        self.label_11.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(140, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(0, 10, 22, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(0, 0, 0)")
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(140, 40, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(230, 10, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(100, 10, 31, 21))
        self.label_5.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(1, 70, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 70, 61, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(300, 10, 51, 21))
        self.label_7.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(300, 40, 51, 21))
        self.label_13.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 100, 91, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 100, 91, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(40, 150, 54, 12))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(200, 100, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 150, 81, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 150, 81, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setGeometry(QtCore.QRect(200, 150, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 210, 131, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setGeometry(QtCore.QRect(0, 130, 91, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setGeometry(QtCore.QRect(100, 130, 91, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setGeometry(QtCore.QRect(0, 180, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        self.label_19.setGeometry(QtCore.QRect(110, 180, 61, 21))
        self.label_19.setStyleSheet("background:rgb(255, 255, 255)")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.centralWidget)
        self.widget_4.setMinimumSize(QtCore.QSize(200, 150))
        self.widget_4.setObjectName("widget_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 40, 231, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 70, 231, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 100, 231, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 130, 231, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 160, 231, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 190, 231, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 10, 51, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_13.setGeometry(QtCore.QRect(80, 10, 171, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.widget_4, 1, 1, 1, 1)
        self.label_6 = VideoLabel(self.centralWidget)
        self.label_6.setMinimumSize(QtCore.QSize(700, 550))
        self.label_6.setAutoFillBackground(True)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        QtWidgetsApplication1Class.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(QtWidgetsApplication1Class)
        self.statusBar.setObjectName("statusBar")
        QtWidgetsApplication1Class.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(QtWidgetsApplication1Class)
        self.toolBar.setObjectName("toolBar")
        QtWidgetsApplication1Class.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(QtWidgetsApplication1Class)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1106, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        QtWidgetsApplication1Class.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(QtWidgetsApplication1Class)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(QtWidgetsApplication1Class)
        QtCore.QMetaObject.connectSlotsByName(QtWidgetsApplication1Class)

    def retranslateUi(self, QtWidgetsApplication1Class):
        _translate = QtCore.QCoreApplication.translate
        QtWidgetsApplication1Class.setWindowTitle(_translate("QtWidgetsApplication1Class", "QtWidgetsApplication1"))
        self.pushButton_5.setText(_translate("QtWidgetsApplication1Class", "垂直圆柱体火焰在水平方向热流密度分布"))
        self.pushButton_14.setText(_translate("QtWidgetsApplication1Class", "垂直圆柱体火焰伤害半径示意图"))
        self.pushButton_15.setText(_translate("QtWidgetsApplication1Class", "垂直圆柱体火焰热流密度分布俯视图"))
        self.pushButton_16.setText(_translate("QtWidgetsApplication1Class", "垂直圆柱体火焰垂直方向的热流密度分布"))
        self.label_3.setText(_translate("QtWidgetsApplication1Class", "X2"))
        self.label_2.setText(_translate("QtWidgetsApplication1Class", "Y1"))
        self.label_4.setText(_translate("QtWidgetsApplication1Class", "Y2"))
        self.label_9.setText(_translate("QtWidgetsApplication1Class", "距离(m)"))
        self.label.setText(_translate("QtWidgetsApplication1Class", "X1"))
        self.label_10.setText(_translate("QtWidgetsApplication1Class", "距离(m)"))
        self.pushButton.setText(_translate("QtWidgetsApplication1Class", "截取辅助标记物"))
        self.pushButton_6.setText(_translate("QtWidgetsApplication1Class", "添加距离"))
        self.lineEdit_3.setText(_translate("QtWidgetsApplication1Class", "187,255,232"))
        self.lineEdit_4.setText(_translate("QtWidgetsApplication1Class", "255,255,255"))
        self.pushButton_7.setText(_translate("QtWidgetsApplication1Class", "添加阈值"))
        self.lineEdit_5.setText(_translate("QtWidgetsApplication1Class", "添加火焰高度"))
        self.lineEdit_6.setText(_translate("QtWidgetsApplication1Class", "添加火焰直径"))
        self.pushButton_8.setText(_translate("QtWidgetsApplication1Class", "添加"))
        self.pushButton_9.setText(_translate("QtWidgetsApplication1Class", "自动分析火焰数据"))
        self.label_16.setText(_translate("QtWidgetsApplication1Class", "火焰高度(m)"))
        self.label_17.setText(_translate("QtWidgetsApplication1Class", "火焰直径(m)"))
        self.label_18.setText(_translate("QtWidgetsApplication1Class", "火焰倾斜角"))
        self.pushButton_3.setText(_translate("QtWidgetsApplication1Class", "沿火焰倾斜方向的热流密度沿X轴分布"))
        self.pushButton_2.setText(_translate("QtWidgetsApplication1Class", "垂直火焰倾斜方向的热流密度沿Y轴分布"))
        self.pushButton_4.setText(_translate("QtWidgetsApplication1Class", "以火焰中心为中心的伤害范围示意图"))
        self.pushButton_10.setText(_translate("QtWidgetsApplication1Class", "假设人在a点不同辐射热流值的伤害范围"))
        self.pushButton_11.setText(_translate("QtWidgetsApplication1Class", "假设人在b点不同辐射热流值的伤害范围"))
        self.pushButton_12.setText(_translate("QtWidgetsApplication1Class", "假设人在c点不同辐射热流值的伤害范围"))
        self.pushButton_13.setText(_translate("QtWidgetsApplication1Class", "添加热流值参数"))
        self.label_15.setText(_translate("QtWidgetsApplication1Class", "TextLabel"))
        self.toolBar.setWindowTitle(_translate("QtWidgetsApplication1Class", "toolBar"))
        self.menu.setTitle(_translate("QtWidgetsApplication1Class", "菜单"))
        self.action.setText(_translate("QtWidgetsApplication1Class", "读取视频"))
from videolabel import VideoLabel
